# Generated by Django 6.1.1 on 2026-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Globe2', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Consultancy Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('target_clients', models.JSONField(blank=True, default=list)),
                ('methodology', models.JSONField(blank=True, default=list)),
                ('standards', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('lead_advisors', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consultancy.consultancycategory')),
            ],
            options={
                'ordering': ['sort_order', '-featured', 'name'],
            },
        ),
    ]
