# Generated by Django 6.1.1 on 2026-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_id', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('length_overall', models.CharField(max_length=50)),
                ('beam', models.CharField(max_length=50)),
                ('draft', models.CharField(max_length=50)),
                ('max_speed', models.CharField(max_length=50)),
                ('bollard_pull', models.CharField(blank=True, default='', max_length=50)),
                ('engine_power', models.CharField(max_length=100)),
                ('hull_material', models.CharField(max_length=100)),
                ('classification_society', models.CharField(max_length=100)),
                ('crew_capacity', models.PositiveIntegerField(default=1)),
                ('delivery_lead_time', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector_id', models.CharField(default='defence', max_length=50)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('lead_time', models.CharField(blank=True, default='', max_length=100)),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('warranty', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
