# Generated by Django 6.1.1 on 2026-10-04 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_file_vessel_image_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['priority', '-featured', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['priority', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Lower numbers appear first. 1 is highest priority; 100 is the default.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Lower numbers appear first. 1 is highest priority; 100 is the default.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
