# Generated by Django 6.1.1 on 2026-10-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('defence', 'Defence'), ('maritime', 'Maritime'), ('industry', 'Industry'), ('consultancy', 'Consultancy'), ('geospatial', 'Geospatial')], max_length=50)),
                ('sector_name', models.CharField(max_length=150)),
                ('client', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Active', 'Active'), ('Delivered', 'Delivered')], default='Delivered', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
