# Generated by Django 6.1.1 on 2026-10-04 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_file_alter_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority', 'sort_order', '-year', 'title', 'id']},
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Lower numbers appear first. 1 is highest priority; 100 is the default.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
