# Generated by Django 6.1.1 on 2026-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'step'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar_id', models.CharField(max_length=50, unique=True)),
                ('badge', models.CharField(default='BEST', max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nova Solutions BD', max_length=150)),
                ('short_name', models.CharField(default='NOVAS', max_length=50)),
                ('founder', models.CharField(default='Mr. Raoson Alom', max_length=150)),
                ('founder_title', models.CharField(default='Founder & CEO, Novas', max_length=150)),
                ('founder_image', models.CharField(default='/assets/founder.png', max_length=500)),
                ('founded_year', models.CharField(default='2012', max_length=20)),
                ('founded_month', models.CharField(default='July 2012', max_length=50)),
                ('team_size', models.CharField(default='24-member specialized engineering & research team', max_length=150)),
                ('tagline', models.CharField(default='Achieving excellence in the field of science, technology and procurement', max_length=255)),
                ('subheading', models.TextField(blank=True, default='')),
                ('address', models.TextField(default='House No-412, Road No-29, Flat-5A-5B-4B, Mohakhali DOHS, Dhaka, Bangladesh')),
                ('phone', models.CharField(default='+8801711264822', max_length=50)),
                ('landline', models.CharField(blank=True, default='9832552', max_length=50)),
                ('email', models.EmailField(default='info@novasbd.com', max_length=254)),
                ('corporate_registry', models.CharField(default='REG-BD-NOVAS-2012', max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.JSONField(blank=True, default=list)),
                ('shipyard_capacity', models.JSONField(blank=True, default=dict)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='HeroBannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('consultancy', 'Consultancy'), ('defence', 'Defence'), ('industry', 'Industry'), ('maritime', 'Maritime'), ('geospatial', 'Geospatial')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20)),
                ('cta_label', models.CharField(blank=True, default='', max_length=100)),
                ('cta_link', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_identifier', 'sort_order', 'id'],
            },
        ),
    ]
