# Generated by Django 6.1.1 on 2026-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='founder_image_file',
            field=models.ImageField(blank=True, help_text='Upload founder photo to Cloudinary', null=True, upload_to='novas/company/'),
        ),
        migrations.AddField(
            model_name='herobannerslide',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload banner image to Cloudinary', null=True, upload_to='novas/banners/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founder_image',
            field=models.CharField(default='/assets/founder.png', help_text='Direct image URL or auto-populated from Cloudinary upload', max_length=500),
        ),
        migrations.AlterField(
            model_name='herobannerslide',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Direct image URL or auto-populated from Cloudinary upload', max_length=500),
        ),
    ]
