# Generated by Django 6.1.1 on 2026-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Shield', max_length=50)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=50)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('target_operators', models.JSONField(blank=True, default=list)),
                ('compliance_standards', models.JSONField(blank=True, default=list)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
