# Generated by Django 6.1.1 on 2026-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image to Cloudinary', null=True, upload_to='novas/sectors/'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Direct image URL or auto-populated from Cloudinary upload', max_length=500),
        ),
    ]
